pipeline {

    agent {
        label 'master'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }

    stages {

        stage('Test Connection 1') {
            steps {
                sh 'ssh root@192.168.10.251 \'ifconfig\''
            }
        }

        stage('Test Connection 2') {
            steps {
                sh 'ssh root@192.168.10.252 \'ifconfig\''
            }
        }

    }

}
